version: '3'

services:
  ktm-web:
    image: ktm/express
    container_name: ktm-web
    restart: always
    build: .
    environment:
      - DB=mongodb://ktm-db:27017/translationdb
    ports:
      - "39010:3000"
    depends_on:
      - ktm-db
  ktm-db:
    image: mongo
    container_name: ktm-db
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "39011:27017"
  mongo-gui:
    container_name: "mongo-gui"
    image: ugleiton/mongo-gui
    restart: always
    ports:
      - "39012:4321"
    environment:
      - MONGO_URL=mongodb://ktm-db:27017
    depends_on:
      - ktm-db

